# Generated by Django 2.1.2 on 2020-05-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='article',
            name='body',
        ),
        migrations.RemoveField(
            model_name='article',
            name='description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
        migrations.AddField(
            model_name='article',
            name='las_moux',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='article',
            name='las_mouy',
            field=models.IntegerField(default=180),
        ),
    ]
