# Generated by Django 2.1.2 on 2020-05-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200504_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='some string', max_length=255),
        ),
    ]
